apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "home-network-pool"
spec:
  blocks:
    - cidr: "192.168.13.232/29"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "home-l2-policy"
spec:
  externalIPs: true
  externalTrafficPolicy: Cluster
  loadBalancerIPs: true
  interfaces:
    - ^vlan13-home$
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: envoy
