apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "home-network-pool"
spec:
  blocks:
    - cidr: "192.168.13.232/29"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vlan13-announcement-policy
spec:
  interfaces:
    - "^vlan13-home$"
  externalTrafficPolicy: Cluster
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      # This targets the Envoy proxy pods specifically
      app.kubernetes.io/name: envoy
